### ISSUE TITLE
Use of ui-router causes leafletData.getMap() to return old map object

### ISSUE THREAD

**Issue by ezk84** [angular-ui/ui-leaflet#250] opened 2016-04-27 03:51 UTC
The scenario is if we have two states that each have a map without id (or with the same id), the second time we load a state, the old map object will be returned from the `leafletData.getMap()` promise. 

This happens specifically when using `ng-animate`, which triggers `ui-router` to not destroy the old scope until after the next scope is displaying and finished animating. This can be worked around by using the `noanimation="true"` attribute on the `ui-view` of interest. 

Plunkr: http://plnkr.co/edit/tmjcITAkJatwlAP5KeFg?p=preview

**Comment by nmccready** [comment] 2016-06-07 17:11
When you leave the context of the map try calling [leafletData. unresolveMap](https://github.com/angular-ui/ui-leaflet/blob/master/src/services/leafletData.js#L30)

**Comment by nmccready** [comment] 2016-06-07 17:50
The problem is ui-router does not always destroy the map if it goes out of view. So you can try and put a `ng-if` around the leaflet directive to try and force destruction so `unresolveMap` is called by leaflet directive [itself](https://github.com/angular-ui/ui-leaflet/blob/master/src/directives/leaflet.js#L139). That ng-if could be triggered via some $state service setting.

**Comment by nmccready** [comment] 2016-06-07 17:51
Also making the map not sticky would help as well. That way the map will get killed when it goes out of view.

**Comment by nmccready** [comment] 2016-06-07 17:52
I also added these comments to avoid confusion and possibly get a PR to fix this https://github.com/angular-ui/ui-leaflet/commit/a9cec1fc6802c2e8bea52621c182dcb77e390659#commitcomment-17774938

**Comment by nmccready** [comment] 2016-06-08 02:46
Also see #261 if your having problems with directiveControls.

**Comment by nmccready** [comment] 2016-06-08 02:47
Closing as I think the workaround provided should help. I will re-open the issue if there is more discussion on this.

**Closed by nmccready** 2016-06-08 02:47 UTC
Labels: workaround

**Comment by ezk84** [comment] 2016-06-13 12:08
@nmccready Now sure what you mean by making the map _not sticky_? I think the workarounds mentioned are indeed the best that can be done for now. 

Unfortunate, since we're relying on scope destruction to maintain the active maps and `ui-router` specifically doesn't destroy the scopes as we expect. 

Only other solution would be to be able to retrieve the map instance given it's id (or not) and a scope by maintaining a scope_id+map_id => map instance mapping. Looks complicated though.

**Comment by nmccready** [comment] 2016-06-13 13:26
You currently do not need the scopeId, as it was a typo in the code. It is specifically the dom id of the map (mapId).

https://github.com/angular-ui/ui-leaflet/blob/1.X/src/services/leafletData.js#L30
